### ISSUE TITLE
Нужна гендерно-верная версия этого "шедевра". Чтоб по матчасти и с вариантом выбора 1488 гендераеров! И Майнер встроить!

### ISSUE THREAD

**Issue by IGR2014** [master-device/HANDOFF_REVIEW#3]
Предлагаю запилить правильную версию этой "потрясающей" игры чтоб дать ответ этим "разработчикам" и показать как надо. А за верность повестке пусть будет Андрей отвечать. Кто за?

**Comment by master-device** [comment]
Ну, это не ко мне, я в геймдизайн не лезу, потому что это самый проклятый вид разработки. Если найдется тот самый герой, который сколотит команду "jeux sans frontières", отстроит свой mother base и запилит свою Частную Игровую Компанию, то отдам им честь.
